Feat/geolocation
DAREng-STACK/DAREng-STACK pull request #16
Opened 2017-08-16 08:33 UTC by dshyeon

2017-08-16 21:15 UTC, picodedan requested changes
in server.js you appear to have added a redirect before the DB call and return,  not sure why we would need to be redirected to index.js there, but that pathing doesn't work. 
It appears you may have removed the gitignore file?

you'll need to fix the above and then do a pull and rebase from the master image to pull in the changes that have already been merged.  your code appears to be missing the client side changes that were merged yesterday.

2017-08-16 21:16 UTC, ddarrach314 commented on server/server.js
> +  res.redirect('/index.js');
why are we redirecting here?

2017-08-16 21:17 UTC, ddarrach314 commented on .gitignore
> -
why is gitignore being removed?

2017-08-17 08:12 UTC, dshyeon commented
fixing

2017-08-17 08:12 UTC, closed without merging